# adapted from https://hub.docker.com/r/projectsigma/gcloud-docker/
# manually built and pushed as praqma/helm-gsutil
FROM projectsigma/gcloud-docker

ENV HELM_VERSION=v2.14.1
# Install Helm
RUN curl -Lo helm-${HELM_VERSION}-linux-amd64.tar.gz https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz && \
    tar -zxvf helm-${HELM_VERSION}-linux-amd64.tar.gz && \
    mv linux-amd64/helm /usr/local/bin/helm && \
    rm helm-${HELM_VERSION}-linux-amd64.tar.gz && \
    rm -rf linux-amd64

# cleanup
RUN rm -rf /var/cache/apk/*
