# adapted from https://github.com/hypertrace/helm-gcs-packager/blob/master/Dockerfile
# manually built and pushed as praqma/helm-gcp
FROM google/cloud-sdk:alpine

# Install Helm
RUN curl -Lo helm-v3.1.2-linux-amd64.tar.gz https://get.helm.sh/helm-v3.1.2-linux-amd64.tar.gz && \
    tar -zxvf helm-v3.1.2-linux-amd64.tar.gz && \
    mv linux-amd64/helm /usr/local/bin/helm && \
    rm helm-v3.1.2-linux-amd64.tar.gz && \
    rm -rf linux-amd64 && \
    helm version

