# adapted from https://github.com/hypnoglow/docker-ci-helm-kit/blob/master/Dockerfile
# manually built and pushed as praqma/helm-aws
FROM docker:17

ENV HELM_VERSION v2.14.1

# download apk index
RUN apk add --update

# common utils
RUN apk add --virtual .builtin-utils curl bash

# aws-cli
RUN apk add --virtual .awscli-runtime-deps python \
    && apk add --virtual .awscli-build-deps py-pip \
    && pip install awscli \
    && apk del --purge .awscli-build-deps


# helm
RUN set -ex \
    && curl -sSL https://storage.googleapis.com/kubernetes-helm/helm-${HELM_VERSION}-linux-amd64.tar.gz | tar xz \
    && mv linux-amd64/helm /usr/local/bin/helm \
    && rm -rf linux-amd64


# cleanup
RUN rm -rf /var/cache/apk/*
