{{- if .Values.ingress }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "app.fullname" $ }}
  labels:
    app: {{ template "app.fullname" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}-{{ .Chart.Name }}
    heritage: {{ .Release.Service }}
  annotations:
  {{- with .Values.ingress.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls_enabled }}
  tls:
    - hosts:
        {{- range .Values.ingress.hosts }}
        - {{ . }}
        {{- end }}
      secretName: {{ .Values.ingress.hosts | first }}-certificate
{{- end }}
  rules:
  {{- if .Values.ingress.default_enabled }}
    - http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "app.fullname" $ }}
              servicePort: {{ $.Values.service.port | default 80 }}
  {{- end }}
  {{- if .Values.ingress.hosts }}
    {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "app.fullname" $ }}
              servicePort: {{ $.Values.service.port | default 80 }}
    {{- end }}
  {{- end }}
{{- end }}
