apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "cyber-dojo.fullname" . }}-nginx
  labels:
    app: {{ template "cyber-dojo.name" . }}
    chart: {{ template "cyber-dojo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount.nginx }}
  selector:
    matchLabels:
      app: {{ template "cyber-dojo.name" . }}-nginx
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "cyber-dojo.name" . }}-nginx
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.nginx.repository }}:{{ .Values.image.nginx.tag }}"
          imagePullPolicy: {{ .Values.image.nginx.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              memory: {{ .Values.resources.nginx.limits.memory }}
            requests:
              memory: {{ .Values.resources.nginx.requests.memory }}
