apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: {{ template "cyber-dojo.name" . }}
    chart: {{ template "cyber-dojo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.web.type }}
  ports:
    - port: {{ .Values.service.web.port }}
      targetPort: {{ .Values.service.web.port }}
      protocol: TCP
  selector:
    app: {{ template "cyber-dojo.name" . }}-web
    release: {{ .Release.Name }}
