apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "cyber-dojo.fullname" . }}-web
  labels:
    app: {{ template "cyber-dojo.name" . }}
    chart: {{ template "cyber-dojo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount.web }}
  selector:
    matchLabels:
      app: {{ template "cyber-dojo.name" . }}-web
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "cyber-dojo.name" . }}-web
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.web.repository }}:{{ .Values.image.web.tag }}"
          imagePullPolicy: {{ .Values.image.web.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            limits:
              memory: {{ .Values.resources.web.limits.memory }}
            requests:
              memory: {{ .Values.resources.web.requests.memory }}
